# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: docker.io/mgautierfr/arx-ci

stages:
  - check
  - build
  - test

fmt:
  stage: check
  script:
   - rustup component add rustfmt
   - cargo fmt --check

build:
  stage: build
  script:
    - rustup --version && cargo --version && rustc --version
    - cargo build --verbose

test:
  script:
    - cargo test --verbose --features in_ci
