[package]
edition = "2021"
name = "arx"
description = "A file archive based on Jubako container"
version = "0.1.0"
authors = ["Matthieu Gautier <mgautier@kymeria.fr>"]
repository = "https://framagit.org/jubako/arx"
license = "MIT"
categories = ["command-line-utilities", "compression", "filesystem"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.15", features = ["derive"] }
jubako = { git = "https://framagit.org/jubako/jubako.git" }
typenum = "1.15.0"
fuser = "0.12.0"
libc = "0.2.134"
lru = "0.8.1"
fxhash = "0.2.1"

[profile.release]
#debug = 1
lto = true
