[package]
name = "arx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.15", features = ["derive"] }
jubako = { version = "0.1.0" }
typenum = "1.15.0"
fuse = "0.3.1"
libc = "0.2.134"
time = "0.1.38"
lru = "0.8.1"

[profile.release]
#debug = 1
lto = true
