[workspace]
members = ["libarx", "arx", "tar2arx", "zip2arx"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.2.0"
authors = ["Matthieu Gautier <mgautier@kymeria.fr>"]
repository = "https://framagit.org/jubako/arx"
license = "MIT"

[workspace.dependencies]
jubako = { git = "https://framagit.org/jubako/jubako.git" }
clap = { version = "4.3.19", features = ["derive"] }
indicatif = "0.17.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
#debug = 1
lto = true
