name: Publication

on:
  release:
    types: [released]

env:
  CARGO_TERM_COLOR: always

jobs:
  do_publication:
    name: Publish on crates.io
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get install -y libfuse-dev
     
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: |
        cargo publish -p libarx
        cargo publish -p arx
        cargo publish -p tar2arx
        cargo publish -p zip2arx
